### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by LiousYao** [Improbable-AI/walk-these-ways#10]
Hi, I ran your script play.py in the fold "scripts". I found that there is a slow but fatal GPU memory leak problem. Could you provide any suggestions about it? Thanks!

**Comment by gmargo11** [comment]
Hi @LiousYao , noticed you closed this and wanted to check in, did you find a fix? I gave a quick try to replicate this issue but didn't see it on my machine. An older version of the code (before initial release) had this issue but I thought adding the line `with torch.no_grad():` had fixed it

-Gabe

**Comment by LiousYao** [comment]
Thanks for your reply! Yes, by using with torch.no_grad(): in the step() and reset() functions, we can fix this issue.
