### ISSUE TITLE
How to visualize the training log in the form of charts?

### ISSUE THREAD

**Issue by chengh-wang** [Improbable-AI/walk-these-ways#18]
Hi,

I've been attempting to utilize Ml-Dash tools to display the progress of my training, but the only available information on "localhost:3001" is output.log and video data. Whenever I choose a different file, the 'charts' section always appears empty. Is there a way to visualize the training progress using charts? Thank you.

<img width="830" alt="Screen Shot 2023-04-03 at 8 22 41 PM" src="https://user-images.githubusercontent.com/30894237/229654853-a8be296c-eabf-45c1-acb1-b082dfef71af.png">

**Comment by gmargo11** [comment]
Hi @chengh-wang ,

That's odd, I'm not sure why the .charts.yml is empty. But it makes sense that would cause this problem. You should populate .charts.yml with:

```

```
