### ISSUE TITLE
deploy in amd64

### ISSUE THREAD

**Issue by BoyuanDeng** [Improbable-AI/walk-these-ways#19]
Hi! bro, i want do try deploy this work in my NUC but nano in go1, so could you please compile lcm_position.cpp in amd64 or send to me state_estimator_lcmt.hpp....(I don't want this code, just  don't want to trouble you),  you can send compiled lcm_position to dengboyuanalan@gmail.com
thank you!

**Comment by gmargo11** [comment]
Hi @BoyuanDeng ,

You can compile https://github.com/Improbable-AI/walk-these-ways/blob/master/go1_gym_deploy/lcm_types/state_estimator_lcmt.lcm into `state_estimator_lcmt.hpp` using `lcm-gen -x state_estimator_lcmt.lcm`, see here for more details: https://github.com/lcm-proj/lcm/blob/master/docs/content/tutorial-cpp.md

-Gabe

**Comment by BoyuanDeng** [comment]
Hi Gabe, so happy that get your reply,thanks!( i success compiled in yesterday)




邓博远
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Improbable-AI/walk-these-ways"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月9日(星期天) 凌晨2:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Improbable-AI/walk-these-ways] deploy in amd64 (Issue #19)





 
Hi @BoyuanDeng ,
 
You can compile https://github.com/Improbable-AI/walk-these-ways/blob/master/go1_gym_deploy/lcm_types/state_estimator_lcmt.lcm into state_estimator_lcmt.hpp using lcm-gen -x state_estimator_lcmt.lcm, see here for more details: https://github.com/lcm-proj/lcm/blob/master/docs/content/tutorial-cpp.md
 
-Gabe
