### ISSUE TITLE
The deployment instructions fail to un-tar docker environment. I believe the instruction should read:

### ISSUE THREAD

**Issue by Robokan** [Improbable-AI/walk-these-ways#23]
the docker .tar file is in the scripts directory and requires root user to install. So the current instructions fail. However if you change it to this it works:

chmod +x installer/install_deployment_code.sh
cd ~/go1_gym/go1_gym_deploy/scripts
sudo ../installer/install_deployment_code.sh

**Comment by gmargo11** [comment]
Thanks for the fix, @Robokan ! I've just made the suggested change to the README with commit 6cc4541fecdd443868e7cc1316875d1cf1711d93

-Gabe
