### ISSUE TITLE
Output test.py

### ISSUE THREAD

**Issue by lucasbrodo** [Improbable-AI/walk-these-ways#33]
Hi @gmargo11,
What kind of behavior should we observe when running `test.py` ?
The robots don't walk in IsaacGym when running the script. They seem to fall on their hind legs.

![isaac_gym](https://github.com/Improbable-AI/walk-these-ways/assets/94857159/810cb836-47c2-4ce5-88d2-d13dba9200bb)
![terminal_output](https://github.com/Improbable-AI/walk-these-ways/assets/94857159/71eb5b48-03d1-4bfc-b4f6-1f782e139eed)

Thank you very much for your feedback and congratulations on your work.

**Comment by gmargo11** [comment]
Hi @lucasbrodo ,

What you describe is the intended behavior of `test.py`. This line: https://github.com/Improbable-AI/walk-these-ways/blob/master/scripts/test.py#L199 sets the actions to zero which corresponds to the pose you're describing. `test.py` just verifies that the simulator runs without error.

To make the robot walk using the learned gaits, you can run `play.py` which sets the actions by evaluating the policy: https://github.com/Improbable-AI/walk-these-ways/blob/master/scripts/play.py#L124

-Gabe
