### ISSUE TITLE
Can't find docker image after sudo ../installer/install_deployment_code.sh

### ISSUE THREAD

**Issue by dhruvkm2402** [Improbable-AI/walk-these-ways#42]
Hello,
When I try to install docker image for the deployment code, it gives me the following error
[Step 1] Extracting docker image...
open /var/lib/docker/tmp/docker-import-137802504/repositories: no such file or directory
How do I resolve it?

**Comment by gmargo11** [comment]
Hi @dhruvkm2402 ,

This install script runs a `docker load` command on the zipped docker image located at `../scripts/deployment_image.tar`

According to this: https://stackoverflow.com/questions/54499389/cant-load-docker-from-saved-tar-image it seems most likely that your `deployment_image.tar` file is corrupted.

You can check for corruption by comparing the md5 checksum, it should match on all machines. Here's mine:
```console
unitree@nx:~/go1_gym/go1_gym_deploy/scripts$ md5sum deployment_image.tar 
ca70e4a10063fa39f026d32b1fe5d88b  deployment_image.tar
```
If yours is different, the file is most likely corrupted. The corruption could have occurred during the download to your local machine (https://github.com/Improbable-AI/walk-these-ways/blob/master/go1_gym_deploy/scripts/send_to_unitree.sh#L3) or when you transferred the file from your machine to the robot (https://github.com/Improbable-AI/walk-these-ways/blob/master/go1_gym_deploy/scripts/send_to_unitree.sh#L6). I'd suggest deleting the tar file from both and running these steps again.
