### ISSUE TITLE
./lcm_position: error while loading shared libraries: liblcm.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by SDU-KIKI** [Improbable-AI/walk-these-ways#48]
When I tried to start the controller with the command: ./start_unitree_sdk.sh, the problem happened. It seemed that the docker haven't installed the lcm correctly?

**Comment by gmargo11** [comment]
Hi @SDU-KIKI ,

It sounds like you may be running `./start_unitree_sdk.sh` inside docker. If so, please try running it outside of docker and let me know if the problem persists. The script is intended to be run on the Jetson Nano's host operating system.

-Gabe

**Comment by SDU-KIKI** [comment]
I tried running it inside docker by :
python3 setup.py install
cd go1_gym_deploy/scripts
python3 deploy_policy.py
When it print the message: "About to calibrate; the robot will stand [Press R2 to calibrate]", I pressed the [R2] of RC, but nothing happened after a while.

**Comment by amrmousa144** [comment]
Add this line to your `.bashrc` to append the path of your venv's lib folder to the system:
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/your/venv/lib`

**Comment by Anchoret13** [comment]
> I tried running it inside docker by : python3 setup.py install cd go1_gym_deploy/scripts python3 deploy_policy.py When it print the message: "About to calibrate; the robot will stand [Press R2 to calibrate]", I pressed the [R2] of RC, but nothing happened after a while.

Hi @SDU-KIKI , I met the same problem. How did you solve that?
