### ISSUE TITLE
training with headless

### ISSUE THREAD

**Issue by zhxiaoyu218** [Improbable-AI/walk-these-ways#54]
Can I disable the isaac gym windows during traning, like --headless

**Comment by gmargo11** [comment]
Hi @zhxiaoyu218,

You can disable the window by setting `headless=True` in `train.py`: replace https://github.com/Improbable-AI/walk-these-ways/blob/f72872927db7cd76be9d3a8dba4cba4a7c1d89d1/scripts/train.py#L255-L256  with `train_go1(headless=True)`

-Gabe
