### ISSUE TITLE
spend too long time deploying the model on GO1

### ISSUE THREAD

**Issue by tenthousandrain** [Improbable-AI/walk-these-ways#56]
hello！when i deploy the pretrain model on GO1，i spend more than 30 mins loading the policy. Is there someting wrong with the robot? I‘m looking forward to your reply.

**Comment by gmargo11** [comment]
Hi @tenthousandrain,

If this issue persists, can you please provide more details about the obstacle you encountered during deployment, such as an error message or the step where the deployment failed?

Thanks
-Gabe
