### ISSUE TITLE
Did this require that I buy one unitree robot dog first? 

### ISSUE THREAD

**Issue by tula-liuxin** [Improbable-AI/walk-these-ways#59]
Thank your works here, that's awesome!
But since I saw it mentioned connecting unitree  serve and it seemingly have to use controller, so I wonder if I have to get a unitree robot dog first, or I still could run it in simulation? 
Sorry to the possible bothering since I am a biggner

**Comment by gmargo11** [comment]
Hi @tula-liuxin ,

Glad you're enjoying the repo!

**You can run the controller in simulation first; no dog is required.**

You'll be able to train and play the walk-these-ways controller for a simulated robot by following the instructions in "Training a Model" section: https://github.com/Improbable-AI/walk-these-ways?tab=readme-ov-file#training-a-model- . You don't need any physical robot for this stage. The next stage, "Deploying a Model", is the only stage that requires a physical Unitree Go1 Edu robot. 

-Gabe

**Comment by tula-liuxin** [comment]
Thank you for your reponse! It's helpful
