### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Li-Guanda** [Improbable-AI/walk-these-ways#62]
the code in 36th and 37th line of go1_gym/envs/base/base_task.py:
     if self.headless == True:
            self.graphics_device_id = self.sim_device_id
will cause “Segmentation fault (core dumped)” in some situations, please consider changing it back to:
     if self.headless == True:
            self.graphics_device_id = -1

**Comment by gmargo11** [comment]
Thanks. Fixed with commit 0e7236b ! -Gabe
