### ISSUE TITLE
entrypoint.sh missing?

### ISSUE THREAD

**Issue by Robokan** [Improbable-AI/walk-these-ways#76]
I am trying to add rl_games to the docker image but when I type 'make build' on the makefile in the docker directory it fails to find entrypoint:

=> CACHED [11/15] RUN apt-get install -y libgl1-mesa-dev libudev1 libudev-dev                   0.0s
 => CACHED [12/15] RUN apt-get install -y libgtk2.0-dev pkg-config                               0.0s
 => CACHED [13/15] RUN pip3 install opencv-python opencv-contrib-python                          0.0s
 => CACHED [14/15] RUN pip3 install rl_games==1.6.1                                              0.0s
 => ERROR [15/15] COPY entrypoint.sh /                                                           0.0s
------
 > [15/15] COPY entrypoint.sh /:
------
failed to compute cache key: failed to calculate checksum of ref ZOYK:45QW:22AP:RFV7:HTO6:PD2A:FRFM:SXP5:TX4N:K2W5:JX3L:U2D7::cxko9ziybrtl7qph3uwme849r: "/entrypoint.sh": not found

Also curious. Are you building this docker file while logged onto the Go1? or are you using a virtual environment on your PC?

**Comment by gmargo11** [comment]
Thanks. Fixed with commit 0e7236b ! 

I built the image on a Jetson development kit. I think it can be built directly on the robot, but the device's limited memory could cause an issue.

-Gabe
