### ISSUE TITLE
the error in go1_gym.envs.base_task.py

### ISSUE THREAD

**Issue by L-lorish** [Improbable-AI/walk-these-ways#78]
The code in the file is:
        self.graphics_device_id = self.sim_device_id
        if self.headless == True:
            self.graphics_device_id = self.sim_device_id

But i think should be modified to:
        self.graphics_device_id = self.sim_device_id
        if self.headless == True:
            self.graphics_device_id = -1

**Comment by gmargo11** [comment]
Thanks. Fixed with commit 0e7236b ! -Gabe
